[ansible.FAccount@scclhubansb01 Server_Patching]$ cat Server_Patching_rhel.yml
---
- name: Patch Red Hat Servers
  hosts: ZabbixServers
  remote_user: ansible.FAccount
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    - name: Update package cache
      package_facts:
        manager: auto

    - name: Check for available updates
      yum:
        list: available
      register: updates

    - name: Install updates if available
      yum:
        name: '*'
        state: latest
      when: updates|length > 0

    - name: Confirm patching
      shell: "rpm -qa --last | grep 'kernel-' | head -n 1"
      register: latest_kernel

    - name: Print confirmation
      debug:
        msg: "Latest installed kernel: {{ latest_kernel.stdout }}"

[ansible.FAccount@scclhubansb01 Server_Patching]$
