[ansible.FAccount@scclhubansb01 Server_Patching]$ cat Server_Health.yml
---
- name: Verify Server Health
  hosts: 10.32.132.202
  remote_user: ansible.FAccount
  become: true
  become_method: sudo
  become_user: root


  tasks:
    - name: Check CPU Usage
      command: mpstat 1 1 | awk '$12 ~ /[0-9.]+/ { print 100 - $12 }' | tail -n 1
      register: cpu_usage_raw

    - name: Convert CPU Usage to Float
      set_fact:
        cpu_usage: "{{ cpu_usage_raw.stdout | float }}"
      when: cpu_usage_raw.stdout is regex('\\d+\\.\\d+')

    - name: Check Memory Usage
      command: free | awk '/^Mem:/ {print $3/$2 * 100}'
      register: mem_usage_raw

    - name: Convert Memory Usage to Float
      set_fact:
        mem_usage: "{{ mem_usage_raw.stdout | float }}"
      when: mem_usage_raw.stdout is regex('\\d+\\.\\d+')

    - name: Print CPU and Memory Usage
      debug:
        msg: |
          Server: {{ ansible_hostname }}
          CPU Usage: {{ cpu_usage | default('No data') }}
          Memory Usage: {{ mem_usage | default('No data') }}

    - name: Verify CPU and Memory Usage > 90%
      debug:
        msg: "CPU or Memory usage is above 90% on {{ ansible_hostname }}"
      when:
        - cpu_usage is defined and cpu_usage > 90
        - mem_usage is defined and mem_usage > 90

[ansible.FAccount@scclhubansb01 Server_Patching]$
